courseinfo/urls.py
from django.urls import path
from courseinfo.views import (
    InstructorList,
    SectionList,
    CourseList,
    SemesterList,
    StudentList,
    RegistrationList,
    InstructorDetail,
    InstructorUpdate,
    InstructorDelete,
    SectionDetail,
    StudentDetail,
    CourseDetail,
    SemesterDetail,
    RegistrationDetail,
    InstructorCreate,
    SectionCreate,
    SectionUpdate,
    SectionDelete,
    CourseCreate,
    CourseUpdate,
    CourseDelete,
    SemesterCreate,
    SemesterUpdate,
    SemesterDelete,
    StudentCreate,
    StudentUpdate,
    StudentDelete,
    RegistrationCreate,
    RegistrationUpdate,
    RegistrationDelete,
)

urlpatterns = [
    #list page
    path('instructor/',
          #option+return
          InstructorList.as_view(),
          name='courseinfo_instructor_list_urlpattern'),

    #data type and parameter, note int:pk no spaces
    #detail page
    path('instructor/<int:pk>/',
          InstructorDetail.as_view(),
          name='courseinfo_instructor_detail_urlpattern'),

    path('instructor/create/',
         InstructorCreate.as_view(),
         name='courseinfo_instructor_create_urlpattern'),

    path('instructor/<int:pk>/update/',
         InstructorUpdate.as_view(),
         name='courseinfo_instructor_update_urlpattern'),

    path('instructor/<int:pk>/delete/',
         InstructorDelete.as_view(),
         name='courseinfo_instructor_delete_urlpattern'),

    path('section/',
         SectionList.as_view(),
         name='courseinfo_section_list_urlpattern'),

    path('section/<int:pk>/',
         SectionDetail.as_view(),
         name='courseinfo_section_detail_urlpattern'),

    path('section/create/',
         SectionCreate.as_view(),
         name='courseinfo_section_create_urlpattern'),

    path('section/<int:pk>/update/',
         SectionUpdate.as_view(),
         name='courseinfo_section_update_urlpattern'),

    path('section/<int:pk>/delete/',
         SectionDelete.as_view(),
         name='courseinfo_section_delete_urlpattern'),

    path('course/',
         CourseList.as_view(),
         name='courseinfo_course_list_urlpattern'),

    path('course/<int:pk>/',
         CourseDetail.as_view(),
         name='courseinfo_course_detail_urlpattern'),

    path('course/create/',
         CourseCreate.as_view(),
         name='courseinfo_course_create_urlpattern'),

    path('course/<int:pk>/update/',
         CourseUpdate.as_view(),
         name='courseinfo_course_update_urlpattern'),

    path('course/<int:pk>/delete/',
         CourseDelete.as_view(),
         name='courseinfo_course_delete_urlpattern'),

    path('semester/',
         SemesterList.as_view(),
         name='courseinfo_semester_list_urlpattern'),

    path('semester/<int:pk>/',
         SemesterDetail.as_view(),
         name='courseinfo_semester_detail_urlpattern'),

    path('semester/create/',
         SemesterCreate.as_view(),
         name='courseinfo_semester_create_urlpattern'),

    path('semester/<int:pk>/update/',
         SemesterUpdate.as_view(),
         name='courseinfo_semester_update_urlpattern'),

    path('semester/<int:pk>/delete/',
         SemesterDelete.as_view(),
         name='courseinfo_semester_delete_urlpattern'),

    path('student/',
         StudentList.as_view(),
         name='courseinfo_student_list_urlpattern'),

    path('student/<int:pk>/',
         StudentDetail.as_view(),
         name='courseinfo_student_detail_urlpattern'),

    path('student/create/',
         StudentCreate.as_view(),
         name='courseinfo_student_create_urlpattern'),

    path('student/<int:pk>/update/',
         StudentUpdate.as_view(),
         name='courseinfo_student_update_urlpattern'),

    path('student/<int:pk>/delete/',
         StudentDelete.as_view(),
         name='courseinfo_student_delete_urlpattern'),

    path('registration/',
         RegistrationList.as_view(),
         name='courseinfo_registration_list_urlpattern'),

    path('registration/<int:pk>/',
         RegistrationDetail.as_view(),
         name='courseinfo_registration_detail_urlpattern'),

    path('registration/create/',
         RegistrationCreate.as_view(),
         name='courseinfo_registration_create_urlpattern'),

    path('registration/<int:pk>/update/',
         RegistrationUpdate.as_view(),
         name='courseinfo_registration_update_urlpattern'),

    path('registration/<int:pk>/delete/',
         RegistrationDelete.as_view(),
         name='courseinfo_registration_delete_urlpattern'),

]

zhao_bo_ez_university/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import RedirectView, TemplateView

from zhao_bo_ez_university.views import redirect_root_view

urlpatterns = [

    # to seperate the urls
    path('',
         RedirectView.as_view(
             pattern_name='about_urlpattern',
             permanent=False
         )),

    path('login/',
         LoginView.as_view(template_name='courseinfo/login.html'),
         name='login_urlpattern'
         ),

    path('logout/',
         LogoutView.as_view(),
         name='logout_urlpattern'
         ),

    # no data only with a template wiew?
    path('about/',
         TemplateView.as_view(
             template_name='courseinfo/about.html'),
         name='about_urlpattern'
         ),

    path('admin/', admin.site.urls),

    path('', include('courseinfo.urls'))

]

courseinfo/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
#tables in database represent by model.class


class Period(models.Model):
    period_id = models.AutoField(primary_key=True)
    period_sequence = models.IntegerField(unique=True)
    period_name = models.CharField(max_length=45, unique=True)

    def __str__(self):
        return '%s' % self.period_name #reference

    class Meta:
        ordering = ['period_sequence'] #order rule


class Year(models.Model):
    year_id = models.AutoField(primary_key=True)
    year = models.IntegerField(unique=True)

    def __str__(self):
        return '%s' % self.year

    class Meta:
        ordering = ['year']


class Semester(models.Model):
    semester_id = models.AutoField(primary_key=True)
    year = models.ForeignKey(Year, related_name='semesters', on_delete=models.PROTECT)
    period = models.ForeignKey(Period, related_name='semesters', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - %s' % (self.year.year, self.period.period_name)
        #'%s' single string

    def get_absolute_url(self):
        return reverse('courseinfo_semester_detail_urlpattern',
                       kwargs={'pk':self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_semester_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_semester_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['year__year', 'period__period_sequence']
        unique_together = ('year', 'period')  #fk



class Course(models.Model):
    course_id = models.AutoField(primary_key=True)
    course_number = models.CharField(max_length=20)
    course_name = models.CharField(max_length=225)

    def __str__(self):
        return '%s - %s' % (self.course_number, self.course_name)
        #overwrite the original one is object 1,2,3

    def get_absolute_url(self):
        return reverse('courseinfo_course_detail_urlpattern',
                       kwargs={'pk':self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_course_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_course_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    #internal class
    class Meta:
        # display by its course num
        ordering = ['course_number', 'course_name']
        # make coursenum and coursename unique
        unique_together = (('course_number','course_name'),)


class Instructor(models.Model):
    instructor_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

    def get_absolute_url(self):
        return reverse('courseinfo_instructor_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_instructor_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_instructor_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name', 'first_name']
        unique_together = (('last_name','first_name'),)


class Student(models.Model):
    student_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    nickname = models.CharField(max_length=45, blank=True, default='')
    #if not has a value, put an empty string''

    def __str__(self):
        #initialize?
        result = ''
        if self.nickname == '':
            result = '%s, %s' % (self.last_name, self.first_name)
        else:
            result = '%s, %s (%s)' % (self.last_name, self.first_name, self.nickname)
        return result
    
    def get_absolute_url(self):
        return reverse('courseinfo_student_detail_urlpattern',
                       kwargs={'pk':self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_student_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_student_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name', 'first_name', 'nickname']
        unique_together =(('last_name','first_name','nickname'),)


class Section(models.Model):
    section_id = models.AutoField(primary_key=True)
    section_name = models.CharField(max_length=10)
    semester = models.ForeignKey(Semester, related_name='sections', on_delete=models.PROTECT)
    course = models.ForeignKey(Course, related_name='sections', on_delete=models.PROTECT)
    #instructor foreig key
    instructor = models.ForeignKey(Instructor, related_name='sections', on_delete=models.PROTECT)
    #why related name = sections view the object? other side?

    def __str__(self):
        return '%s - %s (%s)' % (self.course.course_number, self.section_name, self.semester.__str__())

    def get_absolute_url(self):
        return reverse('courseinfo_section_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_section_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_section_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['course__course_number','section_name', 'semester__semester_name']
        unique_together = (('semester', 'course', 'section_name'),)


class Registration(models.Model):
    registration_id = models.AutoField(primary_key=True)
    student = models.ForeignKey(Student, related_name='registrations', on_delete=models.PROTECT)
    section = models.ForeignKey(Section, related_name='registrations', on_delete=models.PROTECT)


    def __str__(self):
        return '%s / %s' % (self.section, self.student)

    def get_absolute_url(self):
        return reverse('courseinfo_registration_detail_urlpattern',
                       kwargs={'pk':self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_registration_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_registration_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['section', 'student']
        #only can register one time in one course
        unique_together = (('section', 'student'),)
#run migrate build database table that related to models.py

courseinfo/forms.py
from django import forms
from courseinfo.models import Instructor, Section, Course, Semester, Student, Registration


class InstructorForm(forms.ModelForm):
    #inner class meta
    class Meta:
        model = Instructor
        fields = '__all__'

        def clean_first_name(self):
            return self.cleaned_data['first_name'].strip()

        def clean_last_name(self):
            return self.cleaned_data['last_name'].strip()


class SectionForm(forms.ModelForm):
    #inner class meta
    class Meta:
        model = Section
        fields = '__all__'

        def clean_section_name(self):
            return self.cleaned_data['section_name'].strip()


class CourseForm(forms.ModelForm):
    #inner class meta
    class Meta:
        model = Course
        fields = '__all__'

        def clean_course_number(self):
            return self.cleaned_data['course_number'].strip()

        def clean_course_name(self):
            return self.cleaned_data['course_name'].strip()


class SemesterForm(forms.ModelForm):
    #inner class meta
    class Meta:
        model = Semester
        fields = '__all__'

        def clean_Semester_name(self):
            return self.cleaned_data['semester_name'].strip()


class StudentForm(forms.ModelForm):
    #inner class meta
    class Meta:
        model = Student
        fields = '__all__'

        def clean_first_name(self):
            return self.cleaned_data['first_name'].strip()

        def clean_last_name(self):
            return self.cleaned_data['last_name'].strip()

        def clean_nick_name(self):
            return self.cleaned_data['nick_name'].strip()


class RegistrationForm(forms.ModelForm):
    #inner class meta
    class Meta:
        model = Registration
        fields = '__all__'

courseinfo/templates/courseinfo/course_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Course
{% endblock %}

{% block content %}
    <form
        action="{{ course.get_update_url}}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Course</button>
    </form>
{% endblock %}

courseinfo/templates/courseinfo/instructor_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Instructor
{% endblock %}

{% block content %}
    <form
        action="{{ instructor.get_update_url}}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Instructor</button>
    </form>
{% endblock %}

courseinfo/templates/courseinfo/instructor_list.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Instructor List
{% endblock %}

{% block create_button %}
    {% if perms.courseinfo.add_instructor %}
        <a
                href="{% url 'courseinfo_instructor_create_urlpattern' %}"
                class="button button-primary">
            Create New Instructor</a>
    {% endif %}
{% endblock %}

{% block org_content %}
    <h2>Instructor List</h2>
    {% if perms.courseinfo.add_instructor %}
        <div class="mobile">
            <a
                    href="{% url 'courseinfo_instructor_create_urlpattern' %}"
                    class="button button-primary">
                Create New Instructor</a>
        </div>
    {% endif %}
    <ul>
        {% for instructor in instructor_list %}
            <li>
                <a href="{{ instructor.get_absolute_url }}">
                    {{ instructor }}</a>
            </li>
        {% empty %}
            <li><em>There are currently no instructors available.</em></li>
        {% endfor %}
    </ul>
{% endblock %}

courseinfo/templates/courseinfo/registration_confirm_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Delete Registration
{% endblock %}

{% block content %}
    <form
        action="{{ registration.get_delete_url}}"
        method="post">
        {% csrf_token %}
        <p>
            Are you sure that you wanna delete registration {{ registration }}?
        </p>
        <a href="{{ registration.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete Registration</button>
    </form>
{% endblock %}

courseinfo/templates/courseinfo/registration_form.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Create Registration
{% endblock %}

{% block content %}
    <form
        action="{% url 'courseinfo_registration_create_urlpattern'%}"method="post">
        <!--http request-->
        <!--read the detail-->
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Registration</button>
    </form>
{% endblock %}

courseinfo/templates/courseinfo/registration_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Registration
{% endblock %}

{% block content %}
    <form
        action="{{ registration.get_update_url}}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Registration</button>
    </form>
{% endblock %}

courseinfo/templates/courseinfo/section_detail.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Section - {{ section }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ section }}</h2>
                <ul class="inline">
                    {% if perms.courseinfo.change_section %}
                    <li>
                        <a href="{{ section.get_update_url }}"
                           class="button">
                            Edit Section</a></li>
                    {% endif %}
                {% if perms.courseinfo.delete_section %}
                    <li>
                        <a href="{{ section.get_delete_url }}"
                           class="button">
                            Delete Section</a></li>
                {% endif %}
                </ul>

                   <section>
        <table>
            <tr>
                <th>Course:</th>
                <td><a href="{{ course.get_absolute_url }}">{{ course }}</a></td>
            </tr>
            <tr>
                <th>Section Name:</th>
                <td>{{ section.section_name }}</td>
            </tr>
            <tr>
                <th>Semester:</th>
                <td><a href="{{ semester.get_absolute_url }}">{{ semester }}</a></td>
            </tr>

            <tr>
                <th>Instructor:</th>
                <td><a href="{{ instructor.get_absolute_url }}">{{ instructor }}</a></td>
            </tr>
        </table>

    </section>

    <section>
        <h3>Registrations</h3>
        <ul>
            {% for registration in registration_list %}
                <li>
                    <a href="{{ registration.get_absolute_url }}">{{ registration.student }}</a>
                </li>
            {% empty %}
                <li><em>There are currently no students registered for this section.</em></li>
            {% endfor %}
        </ul>
    </section>

            </div>
        </div> <!-- row -->

    </article>
{% endblock %}

courseinfo/templates/courseinfo/section_form.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Create Section
{% endblock %}

{% block content %}
    <form
        action="{% url 'courseinfo_section_create_urlpattern'%}"method="post">
        <!--http request-->
        <!--read the detail-->
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Section</button>
    </form>
{% endblock %}

courseinfo/templates/courseinfo/section_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Section
{% endblock %}

{% block content %}
    <form
        action="{{ section.get_update_url}}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Section</button>
    </form>
{% endblock %}

courseinfo/templates/courseinfo/semester_confirm_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Delete Semester
{% endblock %}

{% block content %}
    <form
        action="{{ semester.get_delete_url}}"
        method="post">
        {% csrf_token %}
        <p>
            Are you sure that you wanna delete semester {{ semester}}?
        </p>
        <a href="{{ semester.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete Semester</button>
    </form>
{% endblock %}

courseinfo/templates/courseinfo/semester_form.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Create Semester
{% endblock %}

{% block content %}
    <form
        action="{% url 'courseinfo_semester_create_urlpattern'%}"method="post">
        <!--http request-->
        <!--read the detail-->
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Semester</button>
    </form>
{% endblock %}

courseinfo/templates/courseinfo/semester_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Semester
{% endblock %}

{% block content %}
    <form
        action="{{ semester.get_update_url}}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Semester</button>
    </form>
{% endblock %}

courseinfo/templates/courseinfo/student_confirm_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Delete Student
{% endblock %}

{% block content %}
    <form
        action="{{ student.get_delete_url}}"
        method="post">
        {% csrf_token %}
        <p>
            Are you sure that you wanna delete student {{ student }}?
        </p>
        <a href="{{ student.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete Student</button>
    </form>
{% endblock %}

courseinfo/templates/courseinfo/student_refuse_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Error Deleting Student
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Student</h2>
        <p>
            You may not delete this student{{ student }}. This student is currently has the following registered courses:
        </p>

        <ul>
            {% for registration in registrations %}
            <li><a href="{{ registration.get_absolute_url }}">{{ registration }}</a></li>
            {% endfor %}
        </ul>

        <p>
            Return to <a href="{% url 'courseinfo_student_list_urlpattern' %}">Student List</a>
        </p>

    </div>
{% endblock %}